# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a403f6136b8c43a46b75f6fb08e7fbd0c433f0f769f2e29c93a23d1b554e60445d1a064487d74971d2799082bf42451d03b3b4039b366faf1ae4d709e7898b19

test:
  secret_key_base: d243bba00634f588101053a154e1e85e0d7f27d7fb6c9fb4863fae600fd139ea1aec2b6b56ce5dfded49d8e0ba4e096eacf9ca92b8a67730609e9120162af73f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
